version: '3.7'

services:
  web:
    build: ./langsitebuilder
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./langsitebuilder/:/usr/src/langsitebuilder/
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=foo